# Generated by Django 3.2.12 on 2023-04-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_desc', models.CharField(max_length=255)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
