# Generated by Django 3.2.12 on 2023-04-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_fooditem_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='item_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fluigispizzakenosha.com%2Fproduct%2Fsalad-small-pan&psig=AOvVaw30Qf7horuHrT5DjOKkIbSO&ust=1680826936670000&source=images&cd=vfe&ved=0CA8QjRxqFwoTCNjcn7X-k_4CFQAAAAAdAAAAABAJ', max_length=1024),
        ),
    ]
