# Generated by Django 3.2.12 on 2023-04-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_fooditem_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='item_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
